#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TIGER_DIR="${DIR}"/../src
TIGER="${TIGER_DIR}"/tiger

RED='\033[0;31m'
GREEN='\033[0;32m'
PURPLE='\033[0;35m'
NC='\033[0m' # No Color

cd "${DIR}"
function OK(){
	echo -e "${GREEN}OK${NC}"
}


while [ $# -ne 0 ]
  do
    correct=${1%.*}.out
    if [ -f "${correct}" ]; then
        echo Removing case "${correct#$DIR/}"...
        if [ -f "${1}" ]; then
            echo -e "${PURPLE}Source code:${NC}"
            cat "${1}"
        fi
        echo -e "${PURPLE}Output:${NC}"
        cat "${correct}"
        read -p "Remove this output? (y/n) " -n 1 -r
        echo    # (optional) move to a new line
        if [[ $REPLY =~ ^[YysS]$ ]]
        then
            rm "${correct}"
        fi
    else
        echo -e "${RED}Output not found.${NC}"
    fi
    shift
done
