#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TIGER_DIR="${DIR}"/../src
TIGER="${TIGER_DIR}"/tiger

RED='\033[0;31m'
GREEN='\033[0;32m'
PURPLE='\033[0;35m'
NC='\033[0m' # No Color

cd "${DIR}"
function OK(){
	echo -e "${GREEN}OK${NC}"
}

function BAD(){
	echo -e "${RED}BAD${NC}"
}

printf "Compiling Tiger... "
make -C "${TIGER_DIR}" >/dev/null 2>&1
if [ $? -ne 0 ]; then
    BAD
    make -C "${TIGER_DIR}"
    exit 1
fi
OK

while [ $# -ne 0 ]
  do
    if [ -f "${1}" ]; then
    
        echo -e "${PURPLE}Source code:${NC}"
        cat "${1}"
        echo -e "${PURPLE}Output:${NC}"
        "${TIGER}" "${1}"
    else
        echo -e "${RED}File not found.${NC}"
    fi
    shift
done
